- .vscode/settings.json
- CHANGELOG.md
- pyproject.toml
Adjusted the vscode formatter settings to correctly override the default python formatter settings.
> Adjusted the vscode formatter settings

- CHANGELOG.md
> Changelog merge fix

- CHANGELOG.md
- pyproject.toml
- Added `Read the Docs`` links to the README
- Fix the Readthedocs build (sc-1178)
- Changed batch API parameter structure (sc-2332)
- Adjusted the vscode formatter settings
- Security update for requests to `>=2.31.0,<2.32.0`
> [DEV] Release/1.0.0

- CHANGELOG.md
- pyproject.toml
- spb_curate/abstract/api/resource.py
- spb_curate/abstract/superb_ai_object.py
- spb_curate/curate/api.py
- tests/test_superb_object.py
- Corrected the Image search endpoint (sc-2141)
Passed all unit tests and E2E tests.
> [DEV] Hotfix/1.0.1

- CHANGELOG.md
- pyproject.toml
- spb_curate/abstract/api/resource.py
- spb_curate/abstract/superb_ai_object.py
- spb_curate/curate/api.py
- tests/test_superb_object.py
- Corrected the Image search endpoint (sc-2141)
> [PROD] Hotfix/1.0.1

- CHANGELOG.md
- pyproject.toml
- spb_curate/abstract/api/resource.py
- spb_curate/abstract/superb_ai_object.py
- spb_curate/curate/api.py
- tests/test_superb_object.py
- Corrected the Image search endpoint (sc-2141)
> [MAIN] Hotfix/1.0.1

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api.py
- Fixed a duplicate issue for bulk create of local images
> [PROD] Hotfix/1.0.2

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api.py
- Fixed a duplicate issue for bulk create of local images
> [MAIN] Hotfix/1.0.2

- CHANGELOG.md
- pyproject.toml
- Model Diagnosis support (sc-2473)
> [DEV] Release/1.1.0

- CHANGELOG.md
- spb_curate/curate/api/curate.py
> [PROD] hotfix/1.1.1

- CHANGELOG.md
- pyproject.toml
> [MAIN] hotfix/1.1.1.post1

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api/curate.py
- Annotation pagination with filtering
> [PROD] Release/1.2.0

- CHANGELOG.md
- pyproject.toml
- spb_curate/http_client.py
- spb_curate/superb_ai_response.py
- tests/test_api_requestor.py
- Parsing logic for non-specified http response codes
- Override default retry logic to include POST requests
> [PROD] Hotfix/1.2.1

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api/curate.py
- spb_curate/http_client.py
- spb_curate/superb_ai_response.py
- tests/test_api_requestor.py
- Parsing logic for non-specified http response codes
- Override default retry logic to include POST requests
> [MAIN] Hotfix/1.2.1

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api/curate.py
- Fixed outdated parameters for update slice and update slice by query
> [DEV] Hotfix/1.2.2

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api/curate.py
- Fixed outdated parameters for update slice and update slice by query
> [PROD] Hotfix/1.2.2

- CHANGELOG.md
- pyproject.toml
- Documentation URL in pyproject
> Update docs url

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api/model_diagnosis.py
- Fixed an issue where iou_type for creating a diagnosis was not being passed properly
> [PROD] hotfix/1.3.1

- CHANGELOG.md
- pyproject.toml
- spb_curate/curate/api/model_diagnosis.py
- Fixed an issue where iou_type for creating a diagnosis was not being passed properly
> [DEV] hotfix/1.3.1

- CHANGELOG.md
- pyproject.toml
- Added upload_image_directory function for Dataset class (sc-3367)
- Added INFO level logs to track the local image upload progress (sc-3368)
- Upload local images asynchronously (sc-3366)
- Retry local image upload on failure (sc-3366)
> [DEV] release/1.4.0

- .readthedocs.yaml
- CHANGELOG.md
- pyproject.toml
> [PROD] Hotfix/1.4.1.post1

- .readthedocs.yaml
- CHANGELOG.md
- pyproject.toml
> [DEV] Hotfix/1.4.1.post1

- spb_curate/curate/api/curate.py
added slice to upload_images_from_directory
> added slice to upload_images_from_directory
